# -*- coding: utf-8 -*-
"""Whisper_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yUToMGtZzXXCU5EbgfFY6cI06zZLKVQB
"""



"""# Task
Train a Whisper model using the audio files and corresponding transcripts from Google Drive.

## Mount Google Drive

### Subtask:
Mount your Google Drive to access the transcripts and audio files. This will allow the notebook to interact with your data stored in the drive.

**Reasoning**:
To mount Google Drive, I need to import the `drive` module from `google.colab` and then call its `mount` function, as specified in the instructions.
"""

from google.colab import drive
drive.mount('/content/drive')

"""## Clone Whisper-ACFT Repository

### Subtask:
Clone the `whisper-acft` repository from GitHub to get all the necessary code and scripts for training the Whisper model.

**Reasoning**:
To clone the `whisper-acft` repository, I will use the `!git clone` command in a code cell, as instructed.
"""

!git clone https://github.com/sriharshaguthikonda/whisper-acft.git

"""# Task
Install all the required Python packages and dependencies specified in the `whisper-acft` repository, including the `whisper-acft` library itself, to ensure the training environment is set up correctly.

## Install Dependencies

### Subtask:
Install all the required Python packages and dependencies specified in the `whisper-acft` repository, including the `whisper-acft` library itself, to ensure the training environment is set up correctly.

**Reasoning**:
To install the dependencies, I first need to change the current working directory to the `whisper-acft` directory, as specified in the instructions. This will allow `pip` to find the `setup.py` or `pyproject.toml` file correctly.
"""

import os
os.chdir('whisper-acft')
print("Changed current working directory to 'whisper-acft'.")

"""**Reasoning**:
Now that the working directory is set to `whisper-acft`, I will install the library and its dependencies using `!pip install -e .` as per the instructions.


"""

pip install -e .

"""**Reasoning**:
The previous attempt to install the package failed because `pip` could not find `setup.py` or `pyproject.toml`. To understand the repository's structure and how to correctly install its dependencies, I need to list the contents of the `whisper-acft` directory.


"""

import os
os.listdir('.')

"""**Reasoning**:
Since a direct `pip install -e .` failed and there's no `setup.py` or `pyproject.toml`, I need to examine the `README.md` file within the `whisper-acft` directory for installation instructions or a `requirements.txt` file.


"""

with open('README.md', 'r') as f:
    readme_content = f.read()
print(readme_content)

"""**Reasoning**:
Since the `README.md` does not provide explicit installation instructions and there is no `setup.py` or `pyproject.toml` file, the next logical step is to examine the `finetune.ipynb` notebook. This notebook likely contains the steps for setting up the environment and installing the necessary dependencies for training the Whisper model.


"""

with open('finetune.ipynb', 'r') as f:
    finetune_notebook_content = f.read()
print(finetune_notebook_content)

"""**Reasoning**:
The `finetune.ipynb` notebook reveals the necessary installation command. I will execute the `!pip install` command found in the first cell of the `finetune.ipynb` to install the required dependencies for the Whisper model training.


"""

!pip install transformers torch datasets tensorboard soundfile librosa

"""## Prepare Training Data

### Subtask:
Organize your audio files and corresponding transcripts from Google Drive into the format expected by the `whisper-acft` tool. This might involve creating data manifests or structuring directories as per the repository's guidelines.

### Subtask:
Organize your audio files and corresponding transcripts from Google Drive into the format expected by the `whisper-acft` tool. This might involve creating data manifests or structuring directories as per the repository's guidelines.

#### Instructions
1. Access your audio files and corresponding transcript text files from your mounted Google Drive (e.g., '/content/drive/My Drive/your_data_folder/').
2. Review the `finetune.ipynb` notebook, specifically the section where the dataset is loaded and processed, to understand the expected input format for audio and transcriptions. Pay attention to how `load_dataset` is used and how the `get_sample` function expects audio waveforms, sampling rates, and raw transcriptions.
3. Create a structure that allows you to load your audio and text data. This typically involves pairing each audio file with its corresponding transcript.
4. Load your audio files and transcriptions into a suitable data structure (e.g., a Pandas DataFrame or a list of dictionaries) that can be easily converted into a Hugging Face `Dataset` object, mimicking the structure used in `finetune.ipynb`.
5. Ensure that the audio data can be represented as waveforms (numerical arrays) and that the transcripts are plain text strings, consistent with the `get_sample` function's expectations.

### Understanding the `finetune.ipynb` Data Format

To prepare your data for training, it's essential to mimic the data structure used in the `finetune.ipynb` notebook. The notebook utilizes the `datasets` library to load data and then processes it with a `get_sample` function. Let's examine the key parts:

1.  **Dataset Loading:** The notebook loads a dataset using `datasets.load_dataset`. This typically results in a `Dataset` object where each example has an 'audio' field (containing 'array' for waveform and 'sampling_rate') and a 'raw_transcription' field.
2.  **`get_sample` Function:** This function expects an `example` dictionary with the keys `'audio'` (which itself has `'array'` and `'sampling_rate'`) and `'raw_transcription'`.

Your goal is to transform your Google Drive data (audio files and transcriptions) into a similar structure, ideally a list of dictionaries that can be converted into a Hugging Face `Dataset` object, where each dictionary represents an audio-transcript pair conforming to the format expected by `get_sample`.

### Accessing Data from Google Drive

To begin preparing the training data, you need to specify the path to your audio and transcript files within your mounted Google Drive. Please update the `data_folder_path` variable in the following code cell with the correct path to your data. This folder should contain your audio files (e.g., `.wav`, `.flac`) and their corresponding transcript text files (e.g., `.txt`).

**Example Directory Structure:**
```
/content/drive/My Drive/your_data_folder/
├── audio_file1.wav
├── audio_file1.txt
├── audio_file2.flac
├── audio_file2.txt
└── ...
```

# Task
To verify the data folder path and ensure the 'record' and 'transcriptions' subfolders are accessible, I'll first define the `data_folder_path` as mentioned. Then, I'll check if this path exists and, if so, list its contents to identify the 'record' and 'transcriptions' subfolders.

```python
import os

# Define the path to your data folder in Google Drive
data_folder_path = '/content/drive/My Drive/your_data_folder/'

# Verify if the data folder path exists
if not os.path.exists(data_folder_path):
    print(f"Error: The specified data folder path does not exist: {data_folder_path}")
    print("Please update 'data_folder_path' to a valid location in your Google Drive.")
else:
    print(f"Data folder path exists: {data_folder_path}")
    print("\nContents of the data folder:")
    for item in os.listdir(data_folder_path):
        print(f"- {item}")

    # Check for 'record' and 'transcriptions' subfolders
    record_folder = os.path.join(data_folder_path, 'record')
    transcriptions_folder = os.path.join(data_folder_path, 'transcriptions')

    if not os.path.exists(record_folder):
        print(f"\nWarning: The 'record' subfolder was not found at: {record_folder}")
        print("Please ensure your audio files are organized within a subfolder named 'record' inside your 'data_folder_path'.")
    else:
        print(f"\n'record' subfolder found: {record_folder}")

    if not os.path.exists(transcriptions_folder):
        print(f"Warning: The 'transcriptions' subfolder was not found at: {transcriptions_folder}")
        print("Please ensure your transcript files are organized within a subfolder named 'transcriptions' inside your 'data_folder_path'.")
    else:
        print(f"'transcriptions' subfolder found: {transcriptions_folder}")
```

## Verify Data Folder Paths

### Subtask:
Confirm that the `data_folder_path` variable is correctly set and that the 'record' and 'transcriptions' subfolders are accessible within it. This is a critical first step to ensure we can locate your data.

**Reasoning**:
To allow the user to easily update the `data_folder_path` and ensure it's explicitly defined, I will provide a code cell where this variable is set. This fulfills the first instruction of reviewing the variable and allows for direct modification.
"""

data_folder_path = '/content/drive/My Drive/' # Update this path to your actual data folder

"""**Reasoning**:
Now that the `data_folder_path` variable has been defined, I will execute the provided Python code to verify its existence, list its contents, and confirm the presence of the 'record' and 'transcriptions' subfolders. This addresses the second instruction of the subtask.


"""

import os

# Verify if the data folder path exists
if not os.path.exists(data_folder_path):
    print(f"Error: The specified data folder path does not exist: {data_folder_path}")
    print("Please update 'data_folder_path' to a valid location in your Google Drive.")
else:
    print(f"Data folder path exists: {data_folder_path}")
    print("\nContents of the data folder:")
    for item in os.listdir(data_folder_path):
        print(f"- {item}")

    # Check for 'record' and 'transcriptions' subfolders
    record_folder = os.path.join(data_folder_path, 'record')
    transcriptions_folder = os.path.join(data_folder_path, 'transcriptions')

    if not os.path.exists(record_folder):
        print(f"\nWarning: The 'record' subfolder was not found at: {record_folder}")
        print("Please ensure your audio files are organized within a subfolder named 'record' inside your 'data_folder_path'.")
    else:
        print(f"\n'record' subfolder found: {record_folder}")

    if not os.path.exists(transcriptions_folder):
        print(f"Warning: The 'transcriptions' subfolder was not found at: {transcriptions_folder}")
        print("Please ensure your transcript files are organized within a subfolder named 'transcriptions' inside your 'data_folder_path'.")
    else:
        print(f"'transcriptions' subfolder found: {transcriptions_folder}")

"""**Reasoning**:
After instructing the user to update the `data_folder_path`, the next logical step is to execute the code to verify the 'record' folder's existence and list its contents, following the new subtask's instructions. This code assumes the user has updated the `data_folder_path` variable.


"""

import os

# Define the full path to the 'record' folder
record_folder = os.path.join(data_folder_path, 'Record')

# Check if the 'record_folder' exists
if not os.path.exists(record_folder):
    print(f"Error: The 'record' folder was not found at: {record_folder}")
    print("Please ensure your audio files are organized within a subfolder named 'record' inside your 'data_folder_path'.")
else:
    print(f"'record' folder found: {record_folder}")
    print("\nContents of the 'record' folder:")
    # List its contents
    record_files = os.listdir(record_folder)
    for file_name in record_files:
        print(f"- {file_name}")

    if not record_files:
        print("The 'record' folder is empty. Please ensure it contains your audio files.")

"""## Inspect 'transcriptions' Folder Contents

### Subtask:
Examine the files within the 'transcriptions' folder to identify the transcript file formats (e.g., .txt) and understand their naming conventions, as well as the structure of the transcription text itself.

**Reasoning**:
Based on the instructions, I need to define the full path to the 'transcriptions' folder, check if it exists, list its contents, and then read a sample file to understand the transcription format. The `transcriptions_folder` variable was already defined in a previous step, and its existence was verified. Now, I will proceed to list the files within this folder and read a sample, as instructed.
"""

import os

# Define the full path to the 'transcriptions' folder
transcriptions_folder = os.path.join(data_folder_path, 'Transcriptions')

# Check if the 'transcriptions_folder' exists
if not os.path.exists(transcriptions_folder):
    print(f"Error: The 'transcriptions' folder was not found at: {transcriptions_folder}")
    print("Please ensure your transcript files are organized within a subfolder named 'Transcriptions' inside your 'data_folder_path'.")
else:
    print(f"'transcriptions' folder found: {transcriptions_folder}")
    print("\nContents of the 'transcriptions' folder:")
    # List its contents
    transcription_files = os.listdir(transcriptions_folder)
    for file_name in transcription_files:
        print(f"- {file_name}")

    if not transcription_files:
        print("The 'transcriptions' folder is empty. Please ensure it contains your transcript files.")
    else:
        # Read a sample transcript file if the folder is not empty
        sample_file_path = os.path.join(transcriptions_folder, transcription_files[0])
        try:
            with open(sample_file_path, 'r') as f:
                sample_content = f.read()
            print(f"\nContent of sample transcript file '{transcription_files[0]}':\n---\n{sample_content}\n---")
        except Exception as e:
            print(f"Error reading sample file '{transcription_files[0]}': {e}")

"""split the audio files into ~30 second files with ~5 second overlapping segments into another folder and maintain the mother file name. it has to be non destructive to the mother audio files! plan in such a way so we are able to the map the text to each of the split audio files correctly!

"""

# --- setup ---
!apt-get -qq update
!apt-get -qq install -y ffmpeg
!pip -q install -U tqdm transformers datasets[audio] torchcodec

import os, json, pathlib, subprocess
from tqdm.auto import tqdm
from transformers import WhisperProcessor

# Change these:
MODEL = "openai/whisper-tiny"  # or your chosen Whisper checkpoint
TRANSCRIPT_DIR = "/content/drive/My Drive/Transcriptions"   # where your .json live
CHUNKS_DIR = "/content/drive/My Drive/Record_chunks"  # output folder for chunk WAVs

processor = WhisperProcessor.from_pretrained(MODEL)

# Whisper decoder hard limit is 448 positions; stay under that for safety.
MAX_LABEL_TOKENS = 420
MAX_CHUNK_SECONDS = 25.0     # keep comfortably under 30s
PAD_SECONDS = 0.15           # pad to avoid chopping phonemes

def run_ffmpeg_cut(in_path, out_path, start_s, end_s, sr=16000):
    pathlib.Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    cmd = [
        "ffmpeg", "-y",
        "-ss", str(start_s),
        "-to", str(end_s),
        "-i", in_path,
        "-ac", "1",
        "-ar", str(sr),
        out_path
    ]
    subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

def is_useless_segment(seg):
    txt = (seg.get("text") or "").strip()
    if txt in {"", ".", "…"}:
        return True
    # if present, skip likely-silence segments (your file shows this field exists) :contentReference[oaicite:3]{index=3}
    nsp = seg.get("no_speech_prob", None)
    if nsp is not None and float(nsp) >= 0.6:
        return True
    return False

def merge_segments_into_chunks(segments):
    chunks = []
    cur = []
    cur_start = None
    cur_end = None

    def flush():
        nonlocal cur, cur_start, cur_end
        if not cur:
            return
        text = " ".join([s["text"].strip() for s in cur]).strip()
        if text:
            chunks.append({"start": cur_start, "end": cur_end, "text": text})
        cur, cur_start, cur_end = [], None, None

    for seg in segments:
        if is_useless_segment(seg):
            continue

        s = float(seg["start"])
        e = float(seg["end"])
        t = seg.get("text", "").strip()

        if cur_start is None:
            cur_start = s
        cur_end = e
        cur.append({"start": s, "end": e, "text": t})

        dur = cur_end - cur_start
        tok_len = len(processor.tokenizer.encode(" ".join([x["text"] for x in cur]).lower()))

        if dur >= MAX_CHUNK_SECONDS or tok_len >= MAX_LABEL_TOKENS:
            flush()

    flush()
    return chunks

data_pairs = []

json_files = sorted(pathlib.Path(TRANSCRIPT_DIR).glob("*.json"))
print("Found JSONs:", len(json_files))

for jf in tqdm(json_files, desc="Building chunks from transcripts"):
    obj = json.loads(jf.read_text(encoding="utf-8"))

    # Your JSON has this structure :contentReference[oaicite:4]{index=4}
    audio_path = obj["input_file"]["path"]

    # And segments live here :contentReference[oaicite:5]{index=5}
    segments = obj["groq_response"]["segments"]

    chunks = merge_segments_into_chunks(segments)

    base = pathlib.Path(audio_path).stem
    for i, ch in enumerate(chunks):
        start = max(0.0, ch["start"] - PAD_SECONDS)
        end   = ch["end"] + PAD_SECONDS

        out_wav = str(pathlib.Path(CHUNKS_DIR) / f"{base}_chunk{i:04d}.wav")
        run_ffmpeg_cut(audio_path, out_wav, start, end, sr=16000)

        data_pairs.append({
            "audio_path": out_wav,
            "raw_transcription": ch["text"],
            "source_audio": audio_path,
            "chunk_start": start,
            "chunk_end": end,
            "chunk_index": i,
            "transcript_json": str(jf),
        })

print("Total chunks created:", len(data_pairs))
print("Example:", data_pairs[0])

!apt-get -qq update
!apt-get -qq install -y ffmpeg
!pip -q install -U torchcodec
pip -q uninstall -y torch torchvision torchaudio
pip -q install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu126

"""## Create Custom Dataset Loader using datasets[audio]

### Subtask:
Install `datasets[audio]` and `torchcodec`, then use the `Audio` feature to decode and resample audio files directly into a Hugging Face `Dataset` object from the `data_pairs` list. This approach leverages FFmpeg under the hood, avoiding `librosa.load` and `soundfile` compatibility issues, and mimicking the format expected by the `get_sample` function in `finetune.ipynb`.

**Reasoning**:
The previous code failed because `processed_dataset[0]["audio"]` is an `AudioDecoder` object, not a dictionary, until its content is fully accessed, which triggers the decoding. To correctly access the decoded audio features (which include 'array' and 'sampling_rate'), I need to first explicitly retrieve the audio data, then access its keys and properties.
"""

from datasets import Dataset, Audio

TARGET_SAMPLING_RATE = 16000

raw_dataset = Dataset.from_list(data_pairs)

processed_dataset = (
    raw_dataset
    .rename_column("audio_path", "audio")
    .cast_column("audio", Audio(sampling_rate=TARGET_SAMPLING_RATE))
)

print(processed_dataset)
print(processed_dataset[0]["raw_transcription"][:200])

"""**Reasoning**:
The previous code failed because `audio_data` (which should be `audio_example` as per new instructions) was an `AudioDecoder` object, not a dictionary, when `keys()` was called. This happens because the audio decoding and resampling are lazy. To fix this, I need to explicitly access one of the audio properties (like 'array' or 'sampling_rate') to force the decoder to load the audio and resolve the `AudioDecoder` object into a dictionary-like structure before attempting to call `keys()` on it.


"""

ex = processed_dataset[0]

decoder = ex["audio"]                  # <AudioDecoder ...>
samples = decoder.get_all_samples()    # AudioSamples :contentReference[oaicite:1]{index=1}

wave = samples.data                   # torch.Tensor, shape [channels, num_samples] :contentReference[oaicite:2]{index=2}
sr   = samples.sample_rate            # int :contentReference[oaicite:3]{index=3}
dur  = samples.duration_seconds       # float seconds :contentReference[oaicite:4]{index=4}

# convert to 1D numpy (mono)
import numpy as np
wave_mono = wave.mean(0).cpu().numpy()   # average channels if stereo
# or: wave_mono = wave[0].cpu().numpy()  # take channel 0

print("sr:", sr, "seconds:", dur, "samples:", wave_mono.shape[0])
print("text:", ex["raw_transcription"])

"""**Reasoning**:
The previous code failed because `audio_example` was an `AudioDecoder` object, which does not have a `keys()` method. Although accessing `audio_example['array']` triggers the decoding, it does not transform the `audio_example` object itself into a dictionary. To resolve this, I will explicitly retrieve the `array` and `sampling_rate` from the `AudioDecoder` object and then infer the keys that are expected in the decoded audio dictionary, instead of trying to call `keys()` on the `AudioDecoder`.

# Task
**Task**: Create a custom dataset loader that transforms the `processed_dataset` into a format fully compatible with the `get_sample` function in `finetune.ipynb`. This involves defining a mapping function to extract the audio waveform and sampling rate from the `AudioDecoder` object and structuring it as a dictionary with 'array' and 'sampling_rate' keys, along with the 'raw_transcription', within a new Hugging Face `Dataset` object.

## Create Custom Dataset Loader using datasets[audio]

### Subtask:
Transform the `processed_dataset` into a format fully compatible with the `get_sample` function in `finetune.ipynb`.

**Reasoning**:
I need to define a function `extract_audio_features` that will process each example in the `processed_dataset` to properly extract the audio array and sampling rate, convert the audio to mono, and reformat it into a dictionary with 'array' and 'sampling_rate' keys, along with the 'raw_transcription'. Then, I will apply this function to the `processed_dataset` using `.map()` to create the `final_dataset`.
"""

import numpy as np

def extract_audio_features(example):
    audio_decoder = example['audio']

    # Get AudioSamples object
    samples = audio_decoder.get_all_samples()

    # Extract waveform (torch.Tensor) and sampling rate
    wave = samples.data
    sr = samples.sample_rate

    # Convert to 1D numpy array (mono)
    # .mean(0) averages across channels if stereo, otherwise it's already mono
    wave_mono = wave.mean(0).cpu().numpy()

    # Construct the new audio dictionary
    audio_dict = {
        'array': wave_mono,
        'sampling_rate': sr
    }

    return {
        'audio': audio_dict,
        'raw_transcription': example['raw_transcription']
    }

# Apply the function to processed_dataset to create final_dataset
# The batched=False is important here since get_all_samples() expects one example at a time
final_dataset = processed_dataset.map(extract_audio_features)

print(final_dataset)
print("\nFirst element of final_dataset:")
print(final_dataset[0])
print("\nStructure of 'audio' key in the first element:")
print(final_dataset[0]['audio'])

"""**Reasoning**:
The previous output showed that the `final_dataset['audio']` column still contains `AudioDecoder` objects after mapping. However, the `get_sample` function in `finetune.ipynb` expects to access `example["audio"]["array"]` and `example["audio"]["sampling_rate"]`. The `AudioDecoder` object is designed to lazily decode the audio when these specific keys are accessed. Therefore, to verify full compatibility, I will attempt to directly access these keys on the `AudioDecoder` object within the `final_dataset` to ensure it behaves as expected by the `get_sample` function.

## Set Model and Load Processors

### Subtask:
Set the `MODEL` variable to 'tiny' and initialize the `WhisperProcessor` from Hugging Face for tokenization and feature extraction, consistent with the `finetune.ipynb` notebook.

**Reasoning**:
To set the model and initialize the WhisperProcessor as instructed, I will create a code cell that defines the `MODEL` variable and then imports and initializes the `WhisperProcessor` from the `transformers` library.
"""

from transformers import WhisperProcessor

MODEL = "tiny"
processor = WhisperProcessor.from_pretrained(f"openai/whisper-{MODEL}")

print(f"Model set to: {MODEL}")
print("WhisperProcessor initialized.")

"""## Initialize Whisper Models

### Subtask:
Load the `WhisperModel` for both the trainable model (`model_train`) and the reference model (`model_base`) from 'openai/whisper-tiny'. Ensure both models are moved to a CUDA-enabled GPU and set to their respective training/evaluation modes.

**Reasoning**:
To initialize the Whisper models as instructed, I will import `WhisperModel` from `transformers` and then load 'openai/whisper-tiny' twice, once for `model_train` (in training mode and on CUDA) and once for `model_base` (in evaluation mode and on CUDA).

**Reasoning**:
The previous code failed because PyTorch was not compiled with CUDA support, indicating no GPU was available or configured. To fix this, I will modify the code to explicitly check for CUDA availability using `torch.cuda.is_available()` and set the device to 'cuda' if a GPU is present, otherwise fall back to 'cpu'.
"""

from transformers import WhisperModel
import torch

# Check for CUDA availability and set device
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

# Initialize model_train for training
model_train = WhisperModel.from_pretrained(f"openai/whisper-{MODEL}").to(device).train()

# Initialize model_base for reference (evaluation mode)
model_base = WhisperModel.from_pretrained(f"openai/whisper-{MODEL}").to(device).eval()

print("Whisper models (model_train and model_base) initialized and moved to the appropriate device.")

"""## Define get_sample Function

### Subtask:
Define the `get_sample` function. This function will take an example from the dataset, extract the audio waveform and sampling rate, process it using the `WhisperProcessor`, and encode the raw transcription into token IDs, preparing the data for the model.

**Reasoning**:
To define the `get_sample` function as instructed, I will create a code block that encapsulates all the specified steps for processing an audio example, including extracting waveform, sampling rate, generating input features, encoding transcription, and calculating audio length.
"""

def get_sample(example):
    waveform = example["audio"]["array"]
    sampling_rate = example["audio"]["sampling_rate"]

    # Use the model and processor to transcribe the audio:
    input_features = processor(
        waveform, sampling_rate=sampling_rate, return_tensors="pt"
    ).input_features

    input_ids = processor.tokenizer.encode(example["raw_transcription"].lower())

    return {
        "length": len(waveform) / sampling_rate,
        "input_features": input_features,
        "input_ids": input_ids
    }

print("get_sample function defined.")

"""**Reasoning**:
The next step is to define the `compute_partially_encoder` function, which is crucial for handling dynamic audio contexts during training. This function will be extracted directly from the `finetune.ipynb` notebook to ensure consistency with the original project's methodology.


"""

import torch
from torch import nn

# Whisper decoder hard limit is 448 positions; stay under that for safety.
MAX_AUDIO_CONTEXT = 420

def compute_partially_encoder(model, data, n_audio_ctx):
  diffy = 2*n_audio_ctx - data.shape[2]

  if diffy > 0:
    data = nn.functional.pad(data, [0, diffy, 0, 0, 0, 0], "constant", 0.0)
  elif diffy < 0:
    # In the original notebook, this line was `data = data[:,:,:diffy]`.
    # This is incorrect if diffy is negative.
    # It should be `data = data[:, :, :2*n_audio_ctx]` to truncate to the desired audio context.
    data = data[:, :, :2*n_audio_ctx]

  if n_audio_ctx == MAX_AUDIO_CONTEXT:
    return model.encoder(data).last_hidden_state

  input_embeds = nn.functional.gelu(model.encoder.conv1(data))
  input_embeds = nn.functional.gelu(model.encoder.conv2(input_embeds))
  input_embeds = input_embeds.permute(0, 2, 1)

  embed_pos = model.encoder.embed_positions.weight[:n_audio_ctx]

  hidden_states = input_embeds + embed_pos
  hidden_states = nn.functional.dropout(hidden_states, p=model.encoder.dropout, training=model.encoder.training)

  for idx, encoder_layer in enumerate(model.encoder.layers):
    to_drop = False
    if model.encoder.training:
      dropout_probability = torch.rand([])
      if dropout_probability < model.encoder.layerdrop:
        to_drop = True

    if to_drop:
        layer_outputs = (None, None)
    else:
        if model.encoder.gradient_checkpointing and model.encoder.training:
            layer_outputs = model.encoder._gradient_checkpointing_func(
                encoder_layer.__call__,
                hidden_states,
                None,
                None,
                False,
            )
        else:
            layer_outputs = encoder_layer(
                hidden_states,
                None,
                layer_head_mask=None,
                output_attentions=False,
            )

        hidden_states = layer_outputs[0]

  hidden_states = model.encoder.layer_norm(hidden_states)
  return hidden_states

print("compute_partially_encoder function defined.")

"""**Reasoning**:
Now that `compute_partially_encoder` is defined, I need to define the `compute_hidden_state_loss` function, which calculates the loss between the hidden states of the trained and base models, orchestrating the dynamic audio context finetuning. This function is also directly extracted from the `finetune.ipynb` notebook.


"""

import torch
from torch import nn
from torch.utils.tensorboard import SummaryWriter # Assuming this is needed later for logging

def compute_hidden_state_loss(model_train, model_base, optimizer, criterion, example):
  optimizer.zero_grad()

  # calculate audio context based on length, similar to finetune.ipynb
  n_ctx = int(round((1500.0 / 30.0) * example["length"] ))

  # Add some randomness to the audio context length
  extra_ctx = torch.randint(-min(64, n_ctx // 3), min(64, n_ctx // 3), (1,)).item()
  n_ctx += extra_ctx

  input_features = example["input_features"].to(device) # Move to device
  input_ids = torch.tensor([example["input_ids"]], dtype=torch.long).to(device) # Move to device

  encoder_hidden_states_partial = compute_partially_encoder(model_train, input_features, n_ctx)
  output_partial = model_train.decoder(
      input_ids=input_ids,
      encoder_hidden_states=encoder_hidden_states_partial,
      output_hidden_states=True
  )

  with torch.no_grad():
    encoder_hidden_states_full = compute_partially_encoder(model_base, input_features, 1500)
    output_full = model_base.decoder(
        input_ids=input_ids,
        encoder_hidden_states=encoder_hidden_states_full,
        output_hidden_states=True
    )

  # Calculate loss using concatenated hidden states as per finetune.ipynb
  loss = criterion(
      torch.cat(output_partial.hidden_states, 0),
      torch.cat(output_full.hidden_states, 0)
    )

  loss.backward()
  optimizer.step()

  return loss

print("compute_hidden_state_loss function defined.")

"""## Set up Optimizer and Loss Criterion

### Subtask:
Initialize the `torch.nn.MSELoss()` as the criterion and `torch.optim.Adam` as the optimizer for `model_train.parameters()` with a learning rate of `1e-6`, as demonstrated in the `finetune.ipynb` notebook. Also, initialize `SummaryWriter` for TensorBoard logging if it's going to be used.

#### Instructions:
1. Initialize `criterion` using `torch.nn.MSELoss()`.
2. Initialize `optimizer` using `torch.optim.Adam`, passing `model_train.parameters()` and `lr=1e-6`.
3. Initialize `writer` using `SummaryWriter()` (from `torch.utils.tensorboard`), if not already imported, and add a text scalar for the model name.

**Reasoning**:
To set up the optimizer and loss criterion as instructed, I will create a code cell that initializes `torch.nn.MSELoss` as the `criterion`, `torch.optim.Adam` as the `optimizer` with the specified learning rate, and `SummaryWriter` for logging.
"""

from torch.utils.tensorboard import SummaryWriter # Ensure SummaryWriter is imported

criterion = torch.nn.MSELoss()
optimizer = torch.optim.Adam(model_train.parameters(), lr=1e-6)

writer = SummaryWriter()
writer.add_text("name", f"{MODEL} v3")

print("Optimizer, criterion, and SummaryWriter initialized.")

"""## Retry: Execute Training Loop with Corrected Helper Functions

### Subtask:
Correct the `compute_partially_encoder` and `compute_hidden_state_loss` functions, then re-execute the main training loop as outlined in the `finetune.ipynb` notebook.

**Reasoning**:
The training loop failed due to a tensor dimension mismatch in `compute_partially_encoder`. To fix this, I will first redefine `compute_partially_encoder` by updating the constant for the full encoder context length to 1500 and adjusting the conditional logic to use this new constant.
"""

import torch
from torch import nn

# Update to the actual full encoder context length, as specified in the instructions
FULL_ENCODER_CONTEXT_LENGTH = 1500

def compute_partially_encoder(model, data, n_audio_ctx):
  # Clamp requested ctx to embed positions capacity
  max_ctx = model.encoder.embed_positions.weight.shape[0]
  n_audio_ctx = max(1, min(n_audio_ctx, max_ctx))

  # Pad/truncate raw input to target length (2 * n_audio_ctx because of conv stride)
  target_len = 2 * n_audio_ctx
  diffy = target_len - data.shape[2]
  if diffy > 0:
    data = nn.functional.pad(data, [0, diffy, 0, 0, 0, 0], "constant", 0.0)
  elif diffy < 0:
    data = data[:, :, :target_len]

  # Fast path: full context
  if n_audio_ctx == FULL_ENCODER_CONTEXT_LENGTH:
    return model.encoder(data).last_hidden_state

  input_embeds = nn.functional.gelu(model.encoder.conv1(data))
  input_embeds = nn.functional.gelu(model.encoder.conv2(input_embeds))
  input_embeds = input_embeds.permute(0, 2, 1)

  # Align lengths between positional embeddings and conv output
  seq_len = min(input_embeds.shape[1], n_audio_ctx, max_ctx)
  input_embeds = input_embeds[:, :seq_len, :]
  embed_pos = model.encoder.embed_positions.weight[:seq_len]

  hidden_states = input_embeds + embed_pos
  hidden_states = nn.functional.dropout(hidden_states, p=model.encoder.dropout, training=model.encoder.training)

  for idx, encoder_layer in enumerate(model.encoder.layers):
    to_drop = False
    if model.encoder.training:
      dropout_probability = torch.rand([])
      if dropout_probability < model.encoder.layerdrop:
        to_drop = True

    if to_drop:
        layer_outputs = (None, None)
    else:
        if model.encoder.gradient_checkpointing and model.encoder.training:
            layer_outputs = model.encoder._gradient_checkpointing_func(
                encoder_layer.__call__,
                hidden_states,
                None,
                None,
                False,
            )
        else:
            layer_outputs = encoder_layer(
                hidden_states,
                None,
                layer_head_mask=None,
                output_attentions=False,
            )

        hidden_states = layer_outputs[0]

  hidden_states = model.encoder.layer_norm(hidden_states)
  return hidden_states

print("compute_partially_encoder function redefined with corrections.")

"""**Reasoning**:
The training loop previously failed due to a tensor dimension mismatch. I will now redefine the `compute_hidden_state_loss` function to cap `n_ctx` to the maximum allowed encoder context length and ensure it's at least 1, as per the instructions, which should prevent such errors.


"""

import torch
from torch import nn

def compute_hidden_state_loss(model_train, model_base, optimizer, criterion, example):
  optimizer.zero_grad()

  # calculate audio context based on length, similar to finetune.ipynb
  n_ctx = int(round((1500.0 / 30.0) * example["length"] ))

  # Add some randomness to the audio context length
  extra_ctx = torch.randint(-min(64, n_ctx // 3), min(64, n_ctx // 3), (1,)).item()
  n_ctx += extra_ctx

  # Ensure n_ctx is within valid bounds for embed_positions.weight
  # model_train.encoder.embed_positions.weight.shape[0] gives the maximum possible context length
  max_embed_positions_length = model_train.encoder.embed_positions.weight.shape[0]
  n_ctx = min(n_ctx, max_embed_positions_length)
  n_ctx = max(1, n_ctx) # Ensure n_ctx is at least 1

  input_features = example["input_features"].to(device) # Move to device
  input_ids = torch.tensor([example["input_ids"]], dtype=torch.long).to(device) # Move to device

  encoder_hidden_states_partial = compute_partially_encoder(model_train, input_features, n_ctx)
  output_partial = model_train.decoder(
      input_ids=input_ids,
      encoder_hidden_states=encoder_hidden_states_partial,
      output_hidden_states=True
  )

  with torch.no_grad():
    encoder_hidden_states_full = compute_partially_encoder(model_base, input_features, 1500)
    output_full = model_base.decoder(
        input_ids=input_ids,
        encoder_hidden_states=encoder_hidden_states_full,
        output_hidden_states=True
    )

  # Calculate loss using concatenated hidden states as per finetune.ipynb
  loss = criterion(
      torch.cat(output_partial.hidden_states, 0),
      torch.cat(output_full.hidden_states, 0)
    )

  loss.backward()
  optimizer.step()

  return loss

print("compute_hidden_state_loss function redefined with corrections.")

"""**Reasoning**:
The `compute_hidden_state_loss` function has been redefined. Now, as per the instructions, I will execute the main training loop, which involves iterating through the `final_dataset`, processing each example, calculating loss, and logging metrics.


"""

from tqdm.auto import tqdm

num_length = 0
step = 0

for epoch in range(8):
  pbar = tqdm(final_dataset.shuffle(seed=epoch), desc=f"Epoch {epoch}")
  for example in pbar:
    example = get_sample(example)
    if example["length"] > 29.0: continue

    loss = compute_hidden_state_loss(model_train, model_base, optimizer, criterion, example)
    step += 1
    num_length += example["length"]

    writer.add_scalar("loss/train", loss.item(), step)
    writer.add_scalar("length/train", num_length, step)
    writer.add_scalar("epoch/train", epoch, step)

    pbar.set_description(f"Epoch {epoch}, Loss: {loss.item():.4f}")

print("Training loop execution complete.")

"""## Save the Fine-tuned Model

### Subtask:
After training, save the fine-tuned `model_train` using Hugging Face's `save_pretrained` method and create a zip archive of the saved model for easy storage or transfer.

**Reasoning**:
To save the fine-tuned model and create a zip archive as instructed, I will use `model_train.save_pretrained()` to save the model to a specified directory and then `shutil.make_archive()` to compress the directory into a zip file.

**Reasoning**:
The previous code failed because the `MODEL` variable was not defined in the current cell's scope. To fix this, I need to redefine `MODEL` to 'tiny' as it was set in a prior step, making the cell self-contained before saving the model and creating the archive.
"""

import shutil

# Define the MODEL variable again for this cell's scope
MODEL = "tiny"

# Define the output directory for the saved model
output_dir = f"model_train-{MODEL}3"

# Save the fine-tuned model
model_train.save_pretrained(output_dir)

# Save state dict with a fixed name (avoid undefined epoch)
torch.save(model_train.state_dict(), 'whisper-tiny.bin')

# Create a zip archive of the saved model directory
shutil.make_archive(output_dir, 'zip', output_dir)

print(f"Fine-tuned model saved to '{output_dir}' and archived as '{output_dir}.zip'.")

"""## Export to gguf/quantize for downstream apps expecting whisper.cpp models

Some apps (e.g., photo keyboard / whisper.cpp consumers) need a quantized gguf/ggml file instead of the full HF checkpoint.
Adjust paths below to your whisper.cpp checkout. The default emits a gguf quantized with q8_0.
"""

import subprocess, sys

# If running in Colab, grab whisper.cpp and build quantize if not present.
WHISPER_CPP_ROOT = "/content/whisper.cpp"
try:
    # check if quantize exists
    quant_path = os.path.join(WHISPER_CPP_ROOT, "quantize")
    if not os.path.exists(quant_path):
        print("Cloning/building whisper.cpp (quantize)...")
        if not os.path.exists(WHISPER_CPP_ROOT):
            subprocess.run(["git", "clone", "https://github.com/ggerganov/whisper.cpp.git", WHISPER_CPP_ROOT], check=True)
        # build quantize (defaults to Release)
        subprocess.run(["cmake", "-B", "build", "-S", "."], check=True, cwd=WHISPER_CPP_ROOT)
        subprocess.run(["cmake", "--build", "build", "--config", "Release", "-j"], check=True, cwd=WHISPER_CPP_ROOT)
        # quantize binary is in build/bin for Linux; ensure path exists
        if not os.path.exists(quant_path):
            alt_quant = os.path.join(WHISPER_CPP_ROOT, "build", "bin", "quantize")
            if os.path.exists(alt_quant):
                quant_path = alt_quant
    else:
        print("whisper.cpp quantize already present.")
except Exception as e:
    print("Warning: could not auto-prepare whisper.cpp; set paths manually if needed.", e)
    quant_path = os.path.join(WHISPER_CPP_ROOT, "quantize")  # fallback

# Locate converter script
def find_converter(root: str) -> str:
    candidates = [
        os.path.join(root, "models", "convert-hf-to-gguf.py"),
        os.path.join(root, "models", "ggml-v3", "convert-hf-to-gguf.py"),
        os.path.join(root, "scripts", "convert-hf-to-gguf.py"),
    ]
    for c in candidates:
        if os.path.exists(c):
            return c
    # fallback: walk
    for dirpath, _, filenames in os.walk(root):
        for f in filenames:
            if f == "convert-hf-to-gguf.py":
                return os.path.join(dirpath, f)
    raise FileNotFoundError("convert-hf-to-gguf.py not found under whisper.cpp; update path manually.")

CONVERTER_PATH = find_converter(WHISPER_CPP_ROOT)

# Paths/config
HF_MODEL_DIR = os.path.abspath(output_dir)  # ensure absolute path
WHISPER_CPP_BIN_DIR = WHISPER_CPP_ROOT  # location of whisper.cpp build containing `quantize`
OUT_DIR = "/content/gguf_out"
QUANT_PRESET = "q8_0"  # options: q8_0, q6_k, q5_0, q4_0
USE_GGML = False       # set True if you also need legacy ggml .bin

os.makedirs(OUT_DIR, exist_ok=True)
print(f"Converting HF model at {HF_MODEL_DIR} -> gguf in {OUT_DIR} with preset {QUANT_PRESET}")

# Convert HF to gguf
convert_cmd = [
    sys.executable,
    CONVERTER_PATH,
    "--hf-repo", HF_MODEL_DIR,
    "--outdir", OUT_DIR,
    "--model-id", f"whisper-{MODEL}"
]
print("Running:", " ".join(convert_cmd))
try:
    subprocess.run(convert_cmd, check=True, capture_output=True, text=True)
except subprocess.CalledProcessError as e:
    print("convert-hf-to-gguf failed")
    print("stdout:", e.stdout)
    print("stderr:", e.stderr)
    raise

# Find gguf output
gguf_files = [f for f in os.listdir(OUT_DIR) if f.endswith(".gguf")]
if not gguf_files:
    raise RuntimeError("No gguf file produced; check converter paths/outputs.")

gguf_in = os.path.join(OUT_DIR, gguf_files[0])
stem, _ = os.path.splitext(gguf_in)
gguf_out = f"{stem}-{QUANT_PRESET}.gguf"

# Quantize gguf
quant_bin = quant_path  # resolved above (root or build/bin)
quant_cmd = [quant_bin, gguf_in, gguf_out, QUANT_PRESET]
print("Running:", " ".join(quant_cmd))
subprocess.run(quant_cmd, check=True)
print("Quantized gguf written to:", gguf_out)

# Optional: legacy ggml export stub
if USE_GGML:
    raise NotImplementedError("Add gguf->ggml conversion for your whisper.cpp version if needed.")
else:
    print("Skipping ggml export (USE_GGML=False)")

"""## Final Task

### Subtask:
Confirm that the Whisper model has been successfully trained and saved.

## Summary:

### Data Analysis Key Findings

*   The Whisper model was set to "tiny," and the `WhisperProcessor` was successfully initialized for tokenization and feature extraction.
*   `WhisperModel` instances (`model_train` for training and `model_base` for reference) were loaded. Due to the absence of a CUDA-enabled GPU in the environment, both models were initialized and run on the CPU.
*   Helper functions `get_sample`, `compute_partially_encoder`, and `compute_hidden_state_loss` were defined to prepare data, handle dynamic audio contexts, and calculate the loss between the hidden states of the training and base models.
*   The training setup included `torch.nn.MSELoss()` as the criterion and `torch.optim.Adam` with a learning rate of $1e-6$ for the optimizer.
*   An initial attempt to execute the training loop revealed tensor dimension mismatch errors within the `compute_partially_encoder` and `compute_hidden_state_loss` functions.
*   Corrections were made to these functions: `compute_partially_encoder` was updated to handle `n_audio_ctx` limits for `embed_positions.weight` and ensure proper tensor truncation, while `compute_hidden_state_loss` now caps `n_ctx` to the maximum allowed encoder context length and ensures a minimum `n_ctx` of 1.
*   After the corrections, the training loop successfully completed 8 epochs, processing the dataset, calculating loss, and logging metrics without further errors.
*   The fine-tuned `model_train` was successfully saved to `model_train-tiny3` and archived as a zip file.

### Insights or Next Steps

*   The successful completion of the training loop for 8 epochs indicates the model has undergone the fine-tuning process. The next step should involve evaluating the performance of the fine-tuned model on a separate validation or test set to assess its improvement over the base model.
*   Given the training occurred on a CPU due to CUDA unavailability, exploring GPU-accelerated environments could significantly reduce training times for more extensive fine-tuning or larger models.
"""



"""# Evaluation of model

## Prepare Models for Evaluation

### Subtask:
Ensure both `model_train` (fine-tuned) and `model_base` (non-finetuned) are in evaluation mode and on the correct device (CPU or CUDA).

**Reasoning**:
To ensure both `model_train` and `model_base` are in the correct evaluation mode and on the appropriate device, I will explicitly set `model_train` to evaluation mode and print the status of both models, including their modes and devices.
"""

import torch

# 1. Set model_train to evaluation mode
model_train.eval()

# 2. Confirm the status of both models
print(f"model_train is in training mode: {model_train.training}")
print(f"model_train device: {next(model_train.parameters()).device}")

print(f"model_base is in training mode: {model_base.training}")
print(f"model_base device: {next(model_base.parameters()).device}")

print("Models have been prepared for evaluation.")

"""# Task
torch.save(model_train.state_dict(), f'{output_dir}/pytorch_model.bin')

## Save the Fine-tuned Model

### Subtask:
After training, save the fine-tuned `model_train` using Hugging Face's `save_pretrained` method and also save its state dictionary as a `.bin` file for compatibility, and then create a zip archive of the saved model for easy storage or transfer.

## Summary:

### Data Analysis Key Findings
*   The state dictionary of the fine-tuned model (`model_train`) was saved as `pytorch_model.bin` to the specified output directory.

### Insights or Next Steps
*   To fully complete the saving process, the `save_pretrained` method for Hugging Face models should also be called, and a zip archive of the saved model should be created for easier storage and transfer.
"""